apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: client-container
          image: sweezed/gl_client:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: INGRESS_HOST
              valueFrom:
                secretKeyRef:
                  name: ingress-host-addr
                  key: INGRESS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client-service
      protocol: TCP
      port: 3000
      targetPort: 3000
