import Head from 'next/head'
import { type AxiosResponse } from 'axios'
import { type NextPageContext } from 'next'
import { buildClient } from '../apiHelpers/build-client'

function Home() {
  return (
    <>
      <Head>
        <title>Group Lottery</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className=''>
        <div className="border-4 bg-sky-400 border-blue-500/100 border-t-0">
          <h1>Group Lottery</h1>
          <h4><i>luck and fun is in the group</i></h4>
        </div>
      </main>
    </>
  )
}

Home.getInitialProps = async (ctx: NextPageContext) => {
  const client = buildClient(ctx)
  const { data }: AxiosResponse<{ message: string }> = await client.get(
    '/api/users/currentuser'
  )

  return { currentUser: data.message || null }
}

export default Home
