name: lint N Pretty
on:
  pull_request:
    branches:
      - 'main'

jobs:
  lintNpretty:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install Dependencies
        run: |
          echo 'Installing dependencies...'
          npm install

      - name: Run Lint
        run: |
          echo 'Running Lint...'
          npx eslint --fix .

      - name: Make Pretty
        run: |
          echo 'Making Pretty...'
          npx prettier --write .

      - name: Commit lint & prettier changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: lint & prettier'
          commit_options: '--no-verify'
          branch: ${{ github.head_ref}}

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Override For Test
        run: echo 'override for test if workflow doesnt have it, becuase its a required status check'
